# Generated by Django 4.2.1 on 2023-06-18 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DNAME', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EMP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ENAME', models.CharField(max_length=100)),
            ],
        ),
    ]
